[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
elf_path = "puzzleleague64.usa.elf"
output_func_path = "RecompiledFuncs"

[patches]
stubs = [
]

ignored = [
]
